In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [5]:
mat = np.array([[1,2,3],[4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10)

np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(4)

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones(4)

np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(5)

np.random.rand(5, 3)

array([[0.26938569, 0.79148472, 0.45575814],
       [0.31301465, 0.92423354, 0.22850213],
       [0.75605165, 0.72717049, 0.67679949],
       [0.59423075, 0.3380114 , 0.04261483],
       [0.47790425, 0.0400487 , 0.37472329]])

In [31]:
# Normal or Gaussian Distribution
np.random.randn(2)

np.random.randn(4, 2)

array([[-1.06984544, -0.38125636],
       [-0.13051222,  0.13465802],
       [-1.61023813, -0.09236264],
       [-1.02700616,  0.83905096]])

In [36]:
# Range [Inclusive, Exclusive [, Dimesnsion])
np.random.randint(1, 100)

np.random.randint(1, 100, 15)

np.random.randint(1, 100, (2, 3))

array([[63, 77,  7],
       [75, 45, 80]])

In [41]:
# Reshape

arr = np.arange(0, 25)
arr

# Sizes of the arrays must be same
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr = np.random.randint(10, 100, (5, 5))

print(arr)

print(arr.min())
print(arr.max())
print(arr.argmax()) # Position of max value
print(arr.argmin()) # Position of min value

[[96 88 38 70 13]
 [91 83 15 23 19]
 [70 65 31 89 16]
 [12 16 11 55 66]
 [53 29 43 27 95]]
11
96
0
17


In [59]:
# Print shape

print(arr.shape)

arr = arr.reshape(25)
print(arr.shape)

print(arr)

(25,)
(25,)
[96 88 38 70 13 91 83 15 23 19 70 65 31 89 16 12 16 11 55 66 53 29 43 27
 95]


In [60]:
# Data type

arr.dtype

dtype('int64')