In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
# Arithmetic operation

print(arr+arr)
print(arr-arr)
print(arr*arr)

print(arr+5)
print(arr-5)
print(arr*5)

print(arr**2)

[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]
[ 5  6  7  8  9 10 11 12 13 14 15]
[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[ 0  5 10 15 20 25 30 35 40 45 50]
[  0   1   4   9  16  25  36  49  64  81 100]


In [7]:
# Division by zero in an np-array does not give an error. It issues an warning. Code execution doenot stop.
print(arr/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [15]:
# Universal Functions

print(np.sqrt(arr))
print(arr)

print(np.exp(arr))

print(np.max(arr))
print(np.min(arr))
print(np.argmax(arr))
print(np.argmin(arr))

print(np.sin(arr))
print(np.log(arr)) # Lof of 0 is -inf

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[ 0  1  2  3  4  5  6  7  8  9 10]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
10
0
10
0
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in log
  
